var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/check/route.js")
R.c("server/chunks/[root-of-the-server]__1zo6cd9._.js")
R.c("server/chunks/lib_12mtyzw._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/lib_04y_i5m._.js")
R.c("server/chunks/[root-of-the-server]__0sd0qcp._.js")
R.c("server/chunks/_0ti2jrs._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/1045_next_1si7ymy._.js")
R.c("server/chunks/lib_terminal-manager_ts_191k15_._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_check_route_actions_0vfk7dc.js")
R.m(120189)
module.exports=R.m(120189).exports
