var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/tasks/route.js")
R.c("server/chunks/_0a0u9u7._.js")
R.c("server/chunks/lib_0y5o54l._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__1v4abmj._.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/lib_ops_catalog_mjs_0pj12ck._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/_0rwqc1r._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_tasks_route_actions_1695ftk.js")
R.m(835261)
module.exports=R.m(835261).exports
