var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/tasks/route.js")
R.c("server/chunks/[root-of-the-server]__1acv7xc._.js")
R.c("server/chunks/lib_1gwqw9w._.js")
R.c("server/chunks/_1pfn52a._.js")
R.c("server/chunks/lib_0s0r_xa._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/lib_1iq5cu7._.js")
R.c("server/chunks/_0s_dhr9._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/_1l5x_65._.js")
R.c("server/chunks/1045_next_1si7ymy._.js")
R.c("server/chunks/[root-of-the-server]__0msr6qi._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_tasks_route_actions_1695ftk.js")
R.m(835261)
module.exports=R.m(835261).exports
