var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/offline/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j7_-wx._.js")
R.c("server/chunks/ssr/node_modules__pnpm_0su_wfi._.js")
R.c("server/chunks/ssr/1045_next_dist_esm_build_templates_app-page_0pxitls.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ict6nd._.js")
R.c("server/chunks/ssr/node_modules__pnpm_05918rt._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pedlb_._.js")
R.c("server/chunks/ssr/_20067zn._.js")
R.c("server/chunks/ssr/1045_next_dist_client_components_1ytbwwz._.js")
R.c("server/chunks/ssr/1045_next_dist_client_components_builtin_forbidden_1l5jl65.js")
R.c("server/chunks/ssr/1045_next_dist_client_components_builtin_unauthorized_0ltjw8d.js")
R.c("server/chunks/ssr/1045_next_dist_client_components_builtin_global-error_0t93ne-.js")
R.c("server/chunks/ssr/_next-internal_server_app_offline_page_actions_0xm3s3w.js")
R.m(221198)
module.exports=R.m(221198).exports
