var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/tasks/[id]/route.js")
R.c("server/chunks/lib_0leu4t3._.js")
R.c("server/chunks/_0ysc91z._.js")
R.c("server/chunks/lib_1gwqw9w._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/[root-of-the-server]__1v5x7dg._.js")
R.c("server/chunks/lib_0s0r_xa._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_0s_dhr9._.js")
R.c("server/chunks/_02qr9dd._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/lib_1iq5cu7._.js")
R.c("server/chunks/_next-internal_server_app_api_tasks_[id]_route_actions_14wrlbl.js")
R.m(18220)
module.exports=R.m(18220).exports
