var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/skills/search/route.js")
R.c("server/chunks/[root-of-the-server]__0y840vv._.js")
R.c("server/chunks/1y1b_next_1e1wihx._.js")
R.c("server/chunks/[root-of-the-server]__1wgt4vo._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/_0p-ovtz._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_next-internal_server_app_api_skills_search_route_actions_01vvs28.js")
R.m(833484)
module.exports=R.m(833484).exports
