var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/workspaces/[id]/tools/plugins/route.js")
R.c("server/chunks/lib_1i6jyx6._.js")
R.c("server/chunks/lib_1t0_d9n._.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/lib_ops_catalog_mjs_0pj12ck._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__1vky7nh._.js")
R.c("server/chunks/[root-of-the-server]__1_la1z2._.js")
R.c("server/chunks/lib_1ptt8t1._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/lib_0trt7eo._.js")
R.c("server/chunks/lib_0k6_76-._.js")
R.c("server/chunks/_0rwqc1r._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/1oeh_server_app_api_workspaces_[id]_tools_plugins_route_actions_0-c_me9.js")
R.m(34715)
module.exports=R.m(34715).exports
