var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/git/sync/route.js")
R.c("server/chunks/lib_1zg-0a_._.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/lib_git_ops_ts_1gg5tjl._.js")
R.c("server/chunks/[root-of-the-server]__1f7-573._.js")
R.c("server/chunks/lib_git_0uy189r._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/lib_0wp4w4n._.js")
R.c("server/chunks/_0rwqc1r._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/[root-of-the-server]__1t3l8d7._.js")
R.c("server/chunks/_next-internal_server_app_api_git_sync_route_actions_1bmxxh1.js")
R.m(812787)
module.exports=R.m(812787).exports
