var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/terminals/[id]/resize/route.js")
R.c("server/chunks/lib_terminal-manager_ts_191k15_._.js")
R.c("server/chunks/1oj-_next_0j9vq6v._.js")
R.c("server/chunks/[root-of-the-server]__0zqgumn._.js")
R.c("server/chunks/[root-of-the-server]__1gdzfyi._.js")
R.c("server/chunks/_1hp2_fo._.js")
R.c("server/chunks/lib_i18n_1-j7942._.js")
R.c("server/chunks/_next-internal_server_app_api_terminals_[id]_resize_route_actions_1xvttmx.js")
R.m(998844)
module.exports=R.m(998844).exports
