var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/git/status/route.js")
R.c("server/chunks/_1hh9cus._.js")
R.c("server/chunks/1045_next_1si7ymy._.js")
R.c("server/chunks/[root-of-the-server]__0_6rkgf._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/_0ti2jrs._.js")
R.c("server/chunks/_next-internal_server_app_api_git_status_route_actions_0yfxghm.js")
R.m(115314)
module.exports=R.m(115314).exports
