var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/localai/route.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/1045_next_dist_esm_build_templates_app-route_1w2hlir.js")
R.c("server/chunks/[root-of-the-server]__0wb5vho._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__1v4abmj._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/lib_ops_catalog_mjs_0pj12ck._.js")
R.c("server/chunks/lib_localai_daemon_ts_07aitya._.js")
R.c("server/chunks/lib_0e9g-f2._.js")
R.c("server/chunks/_0s46uz1._.js")
R.c("server/chunks/_next-internal_server_app_api_localai_route_actions_1kx9hlq.js")
R.m(46525)
module.exports=R.m(46525).exports
