var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/tasks/[id]/queue/[queueId]/route.js")
R.c("server/chunks/[root-of-the-server]__1xgwh2d._.js")
R.c("server/chunks/lib_1gwqw9w._.js")
R.c("server/chunks/[root-of-the-server]__0vyf9z9._.js")
R.c("server/chunks/lib_0sxh8sz._.js")
R.c("server/chunks/lib_0zt5h3b._.js")
R.c("server/chunks/[root-of-the-server]__1-vh5qk._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_0s_dhr9._.js")
R.c("server/chunks/_1wm2a5e._.js")
R.c("server/chunks/lib_1kji5mf._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/lib_1pk9yxo._.js")
R.c("server/chunks/_next-internal_server_app_api_tasks_[id]_queue_[queueId]_route_actions_03644pn.js")
R.m(776082)
module.exports=R.m(776082).exports
