var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/git/auto-land/route.js")
R.c("server/chunks/[root-of-the-server]__0ffum62._.js")
R.c("server/chunks/_211vopq._.js")
R.c("server/chunks/lib_git_auto-land_ts_02-i8l5._.js")
R.c("server/chunks/1045_next_1si7ymy._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/_1l5x_65._.js")
R.c("server/chunks/lib_git_ops_ts_1gg5tjl._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/_next-internal_server_app_api_git_auto-land_route_actions_0d9jpb-.js")
R.m(450002)
module.exports=R.m(450002).exports
