var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/shells/route.js")
R.c("server/chunks/1045_next_dist_esm_build_templates_app-route_1szgdph.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/[root-of-the-server]__0sl5z8r._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/lib_ops_catalog_mjs_0pj12ck._.js")
R.c("server/chunks/_0s46uz1._.js")
R.c("server/chunks/_next-internal_server_app_api_shells_route_actions_1h5ddpf.js")
R.m(399284)
module.exports=R.m(399284).exports
