var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/accounts/route.js")
R.c("server/chunks/[root-of-the-server]__0qy1fou._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/lib_accounts_index_ts_1-9ov07._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_1wm2a5e._.js")
R.c("server/chunks/_next-internal_server_app_api_accounts_route_actions_07-r3hw.js")
R.m(738907)
module.exports=R.m(738907).exports
