var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/localai/search/route.js")
R.c("server/chunks/[root-of-the-server]__0s004ar._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/_0fhqy0y._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/_0h8oc3b._.js")
R.c("server/chunks/_next-internal_server_app_api_localai_search_route_actions_0ldr_ap.js")
R.m(62768)
module.exports=R.m(62768).exports
