var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/tasks/[id]/stream/route.js")
R.c("server/chunks/_0p8gixg._.js")
R.c("server/chunks/[root-of-the-server]__1v5x7dg._.js")
R.c("server/chunks/lib_0s0r_xa._.js")
R.c("server/chunks/lib_1iq5cu7._.js")
R.c("server/chunks/lib_1gwqw9w._.js")
R.c("server/chunks/_02qr9dd._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_0s_dhr9._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/_next-internal_server_app_api_tasks_[id]_stream_route_actions_12zixnj.js")
R.m(574029)
module.exports=R.m(574029).exports
