var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/terminals/untracked/route.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/[root-of-the-server]__09t-t23._.js")
R.c("server/chunks/[root-of-the-server]__0qtnjt0._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/lib_1t0_d9n._.js")
R.c("server/chunks/lib_terminal-manager_ts_191k15_._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/_0fi82af._.js")
R.c("server/chunks/[root-of-the-server]__151fcrh._.js")
R.c("server/chunks/lib_ops_catalog_mjs_0pj12ck._.js")
R.c("server/chunks/_next-internal_server_app_api_terminals_untracked_route_actions_1_kt9ku.js")
R.m(731399)
module.exports=R.m(731399).exports
