var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/terminals/untracked/route.js")
R.c("server/chunks/_182q0z_._.js")
R.c("server/chunks/[root-of-the-server]__1zo6cd9._.js")
R.c("server/chunks/lib_terminal-manager_ts_191k15_._.js")
R.c("server/chunks/[root-of-the-server]__1nzygt4._.js")
R.c("server/chunks/lib_0wkwm1k._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/_1czx-rk._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/1045_next_1si7ymy._.js")
R.c("server/chunks/_next-internal_server_app_api_terminals_untracked_route_actions_1_kt9ku.js")
R.m(731399)
module.exports=R.m(731399).exports
