var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/localai/runtime/route.js")
R.c("server/chunks/_0sou7x2._.js")
R.c("server/chunks/[root-of-the-server]__19drst0._.js")
R.c("server/chunks/lib_localai_109mxw4._.js")
R.c("server/chunks/1y1b_next_1e1wihx._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/_0p-ovtz._.js")
R.c("server/chunks/_next-internal_server_app_api_localai_runtime_route_actions_0xbnw60.js")
R.m(32391)
module.exports=R.m(32391).exports
