var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/local-models/speak/route.js")
R.c("server/chunks/_1gwo5d1._.js")
R.c("server/chunks/_0sou7x2._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__0c6_8_u._.js")
R.c("server/chunks/[root-of-the-server]__040ca6x._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/lib_ops_catalog_mjs_0pj12ck._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/1y1b_next_1e1wihx._.js")
R.c("server/chunks/_1yt-5ep._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_local-models_speak_route_actions_0rfkqy_.js")
R.m(958569)
module.exports=R.m(958569).exports
