var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/v1/workspaces/route.js")
R.c("server/chunks/_0xh7jcm._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__1v5x7dg._.js")
R.c("server/chunks/lib_0s0r_xa._.js")
R.c("server/chunks/lib_1gwqw9w._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/_0fhqy0y._.js")
R.c("server/chunks/lib_1iq5cu7._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_0s_dhr9._.js")
R.c("server/chunks/lib_0ps2987._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/_next-internal_server_app_api_v1_workspaces_route_actions_1rb1td2.js")
R.m(194651)
module.exports=R.m(194651).exports
