var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/git/remote/route.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/[root-of-the-server]__1sk3130._.js")
R.c("server/chunks/1045_next_dist_esm_build_templates_app-route_1v8-cvo.js")
R.c("server/chunks/lib_0wp4w4n._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/_0rwqc1r._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/_next-internal_server_app_api_git_remote_route_actions_0s5vg16.js")
R.m(372484)
module.exports=R.m(372484).exports
