var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/dictation/transcribe/route.js")
R.c("server/chunks/_1g1c426._.js")
R.c("server/chunks/[root-of-the-server]__042z16r._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/1045_next_1si7ymy._.js")
R.c("server/chunks/lib_localai_1l0__s6._.js")
R.c("server/chunks/_1l5x_65._.js")
R.c("server/chunks/_next-internal_server_app_api_dictation_transcribe_route_actions_19wzs8p.js")
R.m(570073)
module.exports=R.m(570073).exports
