var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/pick-folder/route.js")
R.c("server/chunks/[externals]__1csd6we._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_0sou7x2._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/_0p-ovtz._.js")
R.c("server/chunks/1y1b_next_1e1wihx._.js")
R.c("server/chunks/1y1b_next_dist_esm_build_templates_app-route_1gwvumn.js")
R.c("server/chunks/_next-internal_server_app_api_pick-folder_route_actions_0l--3fi.js")
R.m(89129)
module.exports=R.m(89129).exports
