var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ng8_q0._.js")
R.c("server/chunks/ssr/_0_rqrsi._.js")
R.c("server/chunks/ssr/1y1b_next_dist_esm_build_templates_app-page_1mu62r6.js")
R.c("server/chunks/ssr/node_modules__pnpm_1dafe72._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1_cs3sg._.js")
R.c("server/chunks/ssr/node_modules__pnpm_0v_m_bq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-ex47e._.js")
R.c("server/chunks/ssr/_06nrgpu._.js")
R.c("server/chunks/ssr/1y1b_next_dist_client_components_14h6fo9._.js")
R.c("server/chunks/ssr/1y1b_next_dist_client_components_builtin_forbidden_0px9712.js")
R.c("server/chunks/ssr/1y1b_next_dist_client_components_builtin_unauthorized_1qkv44g.js")
R.c("server/chunks/ssr/1y1b_next_dist_client_components_builtin_global-error_0bdobkp.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_0hhsz1j.js")
R.m(755281)
module.exports=R.m(755281).exports
