var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/localai/backends/route.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/lib_localai_109mxw4._.js")
R.c("server/chunks/1045_next_dist_esm_build_templates_app-route_18o46t5.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__1-b1yc1._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/_0s46uz1._.js")
R.c("server/chunks/lib_localai_daemon_ts_07aitya._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/_next-internal_server_app_api_localai_backends_route_actions_1jrq9a9.js")
R.m(479557)
module.exports=R.m(479557).exports
