var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/workspaces/[id]/tools/route.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/lib_1t0_d9n._.js")
R.c("server/chunks/lib_1i6jyx6._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/lib_ops_catalog_mjs_0pj12ck._.js")
R.c("server/chunks/[root-of-the-server]__0u_pn12._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/lib_1ptt8t1._.js")
R.c("server/chunks/_0fi82af._.js")
R.c("server/chunks/lib_0k6_76-._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/[root-of-the-server]__1vky7nh._.js")
R.c("server/chunks/lib_0trt7eo._.js")
R.c("server/chunks/_next-internal_server_app_api_workspaces_[id]_tools_route_actions_13bd1vs.js")
R.m(596742)
module.exports=R.m(596742).exports
