var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/models/route.js")
R.c("server/chunks/lib_1gwqw9w._.js")
R.c("server/chunks/lib_0s0r_xa._.js")
R.c("server/chunks/[root-of-the-server]__09d4xtk._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/_0fhqy0y._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_next-internal_server_app_api_models_route_actions_1h6mkqp.js")
R.m(408784)
module.exports=R.m(408784).exports
