var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/localai/lab/load/route.js")
R.c("server/chunks/_07mkbzu._.js")
R.c("server/chunks/[root-of-the-server]__20r5uoc._.js")
R.c("server/chunks/lib_localai_014vn_j._.js")
R.c("server/chunks/1045_next_1k1flzy._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/_0s46uz1._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/_next-internal_server_app_api_localai_lab_load_route_actions_095309a.js")
R.m(457596)
module.exports=R.m(457596).exports
