var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/localai/lab/load/route.js")
R.c("server/chunks/_0sou7x2._.js")
R.c("server/chunks/[root-of-the-server]__09sq9ny._.js")
R.c("server/chunks/lib_localai_014vn_j._.js")
R.c("server/chunks/1y1b_next_1e1wihx._.js")
R.c("server/chunks/lib_i18n_0-ydydt._.js")
R.c("server/chunks/_0p-ovtz._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_next-internal_server_app_api_localai_lab_load_route_actions_095309a.js")
R.m(678477)
module.exports=R.m(678477).exports
