var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/settings/judge/tiers/route.js")
R.c("server/chunks/_1zefekd._.js")
R.c("server/chunks/[root-of-the-server]__119h-3w._.js")
R.c("server/chunks/lib_0trt7eo._.js")
R.c("server/chunks/lib_154ivng._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/lib_19va9-k._.js")
R.c("server/chunks/_1l5x_65._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/1045_next_1si7ymy._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/[root-of-the-server]__0gs2n_-._.js")
R.c("server/chunks/_next-internal_server_app_api_settings_judge_tiers_route_actions_19emf0x.js")
R.m(766054)
module.exports=R.m(766054).exports
