var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/settings/judge/tiers/route.js")
R.c("server/chunks/_0r9kwlq._.js")
R.c("server/chunks/[root-of-the-server]__119h-3w._.js")
R.c("server/chunks/lib_0trt7eo._.js")
R.c("server/chunks/lib_154ivng._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/lib_19va9-k._.js")
R.c("server/chunks/_0fhqy0y._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/[root-of-the-server]__16_xfur._.js")
R.c("server/chunks/_next-internal_server_app_api_settings_judge_tiers_route_actions_19emf0x.js")
R.m(893384)
module.exports=R.m(893384).exports
