var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/tunnel/hostnames/[id]/route.js")
R.c("server/chunks/1045_next_dist_esm_build_templates_app-route_1armik-.js")
R.c("server/chunks/[root-of-the-server]__0yre7w0._.js")
R.c("server/chunks/lib_terminal-manager_ts_191k15_._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__042z16r._.js")
R.c("server/chunks/_0ti2jrs._.js")
R.c("server/chunks/lib_i18n_0qbo30f._.js")
R.c("server/chunks/[root-of-the-server]__1dmso7h._.js")
R.c("server/chunks/[root-of-the-server]__0aj_0sj._.js")
R.c("server/chunks/1045_next_1si7ymy._.js")
R.c("server/chunks/_next-internal_server_app_api_tunnel_hostnames_[id]_route_actions_1vtz0ju.js")
R.m(731602)
module.exports=R.m(731602).exports
