var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/sessions/route.js")
R.c("server/chunks/[root-of-the-server]__054ojl3._.js")
R.c("server/chunks/lib_i18n_1-j7942._.js")
R.c("server/chunks/lib_auth_ts_0ai-jfb._.js")
R.c("server/chunks/[root-of-the-server]__02xon9e._.js")
R.c("server/chunks/_1qdrbcz._.js")
R.c("server/chunks/1y1b_next_069ghxz._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_sessions_route_actions_1_ff1f5.js")
R.m(441907)
module.exports=R.m(441907).exports
